server:
    port: 8080
    context-path: #/liuzh/

    mvc:
        view:
            prefix: /templates/
            suffix: .ftl
    freemarker:
        cache: false
        request-context-attribute: request
spring:
    datasource:
        url: jdbc:h2:file:~/testdb
        username: sa
        password: sa
        driverClassName: org.h2.Driver
    aop:
        auto: true
        proxy-target-class: true